### ISSUE TITLE
Emails no se están entregando

### ISSUE THREAD

**Issue by astrojuanlu** [Mercado-Social-de-Madrid/ansible-takahe#9]
```
stator  | Traceback (most recent call last):
stator  |   File "/takahe/stator/models.py", line 202, in transition_attempt
stator  |     next_state = current_state.handler(self)
stator  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
stator  |   File "/takahe/users/models/password_reset.py", line 25, in handle_new
stator  |     send_mail(
stator  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/__init__.py", line 87, in send_mail
stator  |     return mail.send()
stator  |            ^^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
stator  |     return self.get_connection(fail_silently).send_messages([self])
stator  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
stator  |     new_conn_created = self.open()
stator  |                        ^^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 94, in open
stator  |     self.connection.login(self.username, self.password)
stator  |   File "/usr/local/lib/python3.11/smtplib.py", line 739, in login
stator  |     (code, resp) = self.auth(
stator  |                    ^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/smtplib.py", line 642, in auth
stator  |     (code, resp) = self.docmd("AUTH", mechanism + " " + response)
stator  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/smtplib.py", line 432, in docmd
stator  |     return self.getreply()
stator  |            ^^^^^^^^^^^^^^^
stator  |   File "/usr/local/lib/python3.11/smtplib.py", line 405, in getreply
stator  |     raise SMTPServerDisconnected("Connection unexpectedly closed")
stator  | smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

**Comment by astrojuanlu** [comment]
it was an authentication problem in disguise

**Comment by astrojuanlu** [comment]
Volvió a ocurrir

**Comment by astrojuanlu** [comment]
Arreglado de nuevo.

**Comment by astrojuanlu** [comment]
Recuérdese que los caracteres especiales tienen que ir codificados.

https://github.com/jointakahe/takahe/blob/b2223ddf425ec7755d9f1b3883f7e9f7bc06df5e/takahe/settings.py#L400-L402
